### ISSUE TITLE
Thanks! When i try to output the video, it will show the error the "videocontrol" has no attribute "cutter"?

### ISSUE THREAD

**Issue by buloseshilili** [kanehekili/VideoCut#15]
How ti fix it?thanks  again!

**Comment by kanehekili** [comment]
Can you reproduce this error? Which steps did you take before that error happened? It is nearly impossible to fix an error with no information.

**Comment by buloseshilili** [comment]
Yeah, sure. Just try to output cutted video, after choose start and stop frame, try to save. Here is the detail shown in the warning.
Traceback (most recent call last):
*  File "C:/Users/Bugs/Desktop/videocut/VideoCut.py", line 1752, in _cleanupWorker
    if self.cutter is None or self.cutter.wasAborted():
*AttributeError: 'VideoControl' object has no attribute 'cutter'
Thank you!

**Comment by buloseshilili** [comment]
Yeah, sure. Just try to output cutted video, after choose start and stop frame, try to save. Here is the detail shown in the warning.
Traceback (most recent call last):
*  File "C:/Users/Bugs/Desktop/videocut/VideoCut.py", line 1752, in _cleanupWorker
    if self.cutter is None or self.cutter.wasAborted():
*AttributeError: 'VideoControl' object has no attribute 'cutter'
Thank you!

**Comment by kanehekili** [comment]
Ok,I have never tested it on Windows, the binaries are compiled against
native Linux. I guess you are using the WSL. Since I don't have any
Windows, it might be difficult to find the error. I will look into it.
Thanks for reporting

buloseshilili ***@***.***> schrieb am Mi., 24. Nov. 2021,
05:54:

**Comment by kanehekili** [comment]
OK, I could reproduce it. I'll change the error handling at this place.
This happens if you do not have ffmpeg installed or an ffmpeg version which is less than version 3.0.
You would need to install ffmpeg  in WSL like this:
`sudo apt-get install ffmpeg`

The next fix will have a better error message. Thanks for reporting the error.

**Comment by buloseshilili** [comment]
Thanks, but I have been update ffmpeg to 4.3 in anconda, not run in WSL, I will try to run in linux. It seems to lack the function ‘cutter' in class 'videocontrol', the error message is that, I tried to locate the ’cutter‘ function inside, but I couldn 't find it.Can you save files properly on linux ?

**Comment by kanehekili** [comment]
No, we're mutlithreading here - The cutter error has been eliminated, the correct error message displayed

**Comment by kanehekili** [comment]
Try the latest build -and thanks again for pointing me to this error
