### ISSUE TITLE
Editing subtitles with video - mkv container

### ISSUE THREAD

**Issue by lxs602** [kanehekili/VideoCut#16]
Hi,

I read your post here:
https://askubuntu.com/questions/1304004/how-to-edit-mkv-with-subtitles-and-keep-the-subs

I would find it useful to be able to edit video and subtitles at the same time, for occasional films.  

It is a little time consuming to using a video editor to make cuts, then a subtitle editor to make all the same cuts to the subtitles.

However, when I tried to edit a video with soft subtitles (.srt) within an mkv container. VideoCut did not seem to import them.

I have uploaded sample video files below, from before and after trimming with VideoCut. The subtitles do not make it into the output file.

Are subtitles supported for the mkv container?

Input:
https://github.com/lxs602/Test/blob/main/DEFA%20-%20East%20German%20trailer%20subs.mkv

Output:
https://github.com/lxs602/Test/blob/main/DEFA%20-%20East%20German%20trailer%20subs-cut.mkv

Log from terminal:

> user@user-pc:~/Downloads/videocut$ VideoCut 
>using CV3
>qt5ct: using qt5ct plugin
>libpng warning: iCCP: known incorrect sRGB profile
>qt5ct: D-Bus global menu: no
>4.2
>['/opt/videocut/ffmpeg/bin/V4/remux5', '-i', '/home/user/Videos/DEFA - East German trailer subs.mkv', '-s', '00.000,20.720', >'/home/user/Videos/DEFA - East German trailer subs-cut.mkv']
><Input #0, matroska,webm, from '/home/luke/Videos/DEFA - East German trailer subs.mkv':
><  Metadata:
><    ENCODER         : Lavf58.29.100
><  Duration: 00:00:30.98, start: 0.000000, bitrate: 6462 kb/s
><    Stream #0:0: Video: mpeg2video (Main), yuv420p(tv, top first), 720x576 [SAR 16:15 DAR 4:3], SAR 1:1 DAR 5:4, 25 fps, >>25 tbr, 1k tbn, 50 tbc (default)
><    Metadata:
><      DURATION        : 00:00:30.640000000
><    Stream #0:1: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s (default)
><    Metadata:
><      DURATION        : 00:00:30.744000000
><    Stream #0:2: Subtitle: subrip
><    Metadata:
><      DURATION        : 00:00:30.979000000
><Registered 4 decoding threads
><MPEG2 set to PS-stream
>.<Video bitrate: 6462640
><Audio: sample rate: 48000 bitrate: 192000
><Output #0, matroska, to '/home/user/Videos/DEFA - East German trailer subs-cut.mkv':
><    Stream #0:0: Video: mpeg2video (Main), yuv420p(tv, top first), 720x576 [SAR 16:15 DAR 4:3], q=2-31, 25 fps
><    Side data:
><      cpb: bitrate max/min/avg: 96939600/4308426/6462640 buffer size: 2072576 vbv_delay: -1
><    Stream #0:1: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s
><Video length is about 20.72 seconds
><Mux video - Offset: 0 (0.000) fps: 25.000 audio -offset 240 (0.240) delta:-240 (-0.240)
><First IFrame DTS found: 0, normalized: 0 (0.000) mainOffset: 240 (0.24000) voutDelta:40.000
><Video tbi: 1000 tbo: 1000 ; Audio tbi: 1000 tbo: 1000
><Video IN: matroska,webm long:Matroska / WebM
><Video OUT: matroska long:Matroska
><*Done*
><Args: /home/user/Videos/DEFA - East German trailer subs.mkv -> /home/user/Videos/DEFA - East German trailer subs-cut.mkv

Additionally, in the documentation it mentions that Videocut may not cut to exact frames. 

I think, though, that it would be useful to know exactly where you are cutting... 

For example, I know that some video editors cut to keyframes, so this is just a suggestion for something which I think would be beneficial.

Best wishes,

L

**Comment by kanehekili** [comment]
Thanks, I'll downloaded the files and will inspect them. 
**rewritten**
I think I understood your point: You would like to know where the I frames are at cutting/viewing time. (Like a red dot at the top right)
Well, I'd like this as well - but with the usage of OpenCV I can't. Currently I just dump the stream to OpenCV and it displays it. I'd need a complete different viewer (preferably a SDL window) where I have control over search, packet etc... 
I am investigating another approach via mpv (also to make the dependencies smaller), where I can get more infos out of  the displayed packages. 
Nonetheless, I would have to iterate once over all packets in order to find the keyframes...

**Comment by kanehekili** [comment]
Your "cut" seems to be broken, it shows only a small part of the picture  - my working version seems to fix it. 
I've cut your original with the "remux" Videomuxer.  "remux" can't handle the SRT /S_TEXT/UTF-8 text, whereas the ffmpeg option can. This seems to be a flaw (or misunderstanding from my side) concerning the SRT codecs in libav: it tells me that there is no text. 
Anyhow,  I could not see any "subtitles" in your "original" file, I think "Der Untertan 1951" was burned in - so no sub. Could you provide me with a part that displays a subtitle? 

You could add the srt file as "mov_text" before editing: see [here](https://stackoverflow.com/questions/7240247/add-srt-subtitle-to-video-with-ffmpeg). 
In order to add a SRT to an mp4 container, you may issue:
`ffmpeg -i infile.mp4 -f srt -i infile.srt -c:v copy -c:a copy -c:s mov_text outfile.mp4` 
this is about the gist of the link above... 
 I will try provide an option to do this with Videocut.

**Comment by kanehekili** [comment]
Concerning the information of an I frame: I just started to work with the mpv backend (instead of opencv) , which will give me this information. So I'll include your idea in a future version. Thanks for  pointing me into this direction.

**Comment by lxs602** [comment]
> Concerning the information of an I frame: I just started to work with the mpv backend (instead of opencv) , which will give me this information. So I'll include your idea in a future version. Thanks for pointing me into this direction.

That was just what I thought as a user. Hope it was helpful.

> Anyhow, I could not see any "subtitles" in your "original" file, I think "Der Untertan 1951" was burned in - so no sub. Could you provide me with a part that displays a subtitle?

I'm surprised you couldn't see the UTF8 subtitles in the original file... (You are right that "Der Untertan 1951" is burnt in). I can view the subtitles using VLC or mpv after enabling the subtitle track...

I can upload another trailer with subtitles if you like.

Using mediainfo gives the following:

```
user@user-pc:~/Downloads$ mediainfo DEFA\ -\ East\ German\ trailer\ subs.mkv 
General
Unique ID                                : 45152231732630484500031202464565958581 (0x21F800E65B8D89CBFE56EC87146217B5)
Complete name                            : DEFA - East German trailer subs.mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 23.9 MiB
Duration                                 : 30 s 979 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 6 463 kb/s
Writing application                      : Lavf58.29.100
Writing library                          : Lavf58.29.100
ErrorDetectionType                       : Per level 1

Video
ID                                       : 1
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings                          : CustomMatrix / BVOP
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : M=3, N=12
Format settings, picture structure       : Frame
Codec ID                                 : V_MPEG2
Codec ID/Info                            : MPEG 1 or 2 Video
Duration                                 : 30 s 640 ms
Bit rate mode                            : Variable
Bit rate                                 : 6 142 kb/s
Maximum bit rate                         : 9 000 kb/s
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Interlaced
Scan type, store method                  : Separated fields (2 fields per block)
Scan order                               : Top Field First
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.592
Time code of first frame                 : 10:00:00:00
Time code source                         : Group of pictures header
GOP, Open/Closed                         : Open
Stream size                              : 22.4 MiB (94%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited

Audio
ID                                       : 2
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 2
Codec ID                                 : A_MPEG/L2
Codec ID/Hint                            : MP2
Duration                                 : 30 s 504 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Delay relative to video                  : 240 ms
Stream size                              : 715 KiB (3%)
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 30 s 979 ms
Default                                  : No
Forced                                   : No
```
Here is the srt file:

```
1
00:00:01,901 --> 00:00:02,413
Sit!

2
00:00:04,421 --> 00:00:05,172
Stand!

3
00:00:05,381 --> 00:00:06,371
Sit!

4
00:00:06,581 --> 00:00:07,298
Stand!

5
00:00:07,741 --> 00:00:08,253
One...

6
00:00:08,821 --> 00:00:10,619
Two, three

7
00:00:21,141 --> 00:00:22,700
Only on the battlefield

8
00:00:23,381 --> 00:00:28,171
amid blood and iron, can
a nation's might be forged.

9
00:00:29,261 --> 00:00:30,979
The Kaiser's Lackey
```

**Comment by kanehekili** [comment]
Yup, you are right. I tried your example, but neither ffmpeg nor the videocut muxer could display those subtitles. VideocutMuxer doesn't even see them, ffmpeg (which is not as precise in cutting, hence the videocut muxer) sees them but does not show them. I will use your samples for more testing, but can't promise anything.

**Comment by lxs602** [comment]
Hi, I wouldn't worry.  Please do as you see best, as it is your project after all.

It is strange that ffmpeg did not recognise the subtitles for you... I muxed the video with the subtitles using:
> ffmpeg -i DEFA\ -\ East\ German\ trailer\ subs.mkv -c:v null -c:a null DEFA\ -\ East\ German\ trailer\ subs.txt

I was then able to extract the subtitles using:
> ffmpeg -i DEFA\ -\ East\ German\ trailer\ subs.mkv DEFA\ -\ East\ German\ trailer\ subs.srt

ffmpeg version and output to null:
> user@user-pc:~/Videos/Downloads$ ffmpeg -i DEFA\ -\ East\ German\ trailer\ subs.mkv -f null -
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'DEFA - East German trailer subs.mkv':
  Metadata:
    ENCODER         : Lavf58.29.100
  Duration: 00:00:30.98, start: 0.000000, bitrate: 6462 kb/s
    Stream #0:0: Video: mpeg2video (Main), yuv420p(tv, top first), 720x576 [SAR 16:15 DAR 4:3], SAR 1:1 DAR 5:4, 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      DURATION        : 00:00:30.640000000
    Stream #0:1: Audio: mp2, 48000 Hz, stereo, s16p, 192 kb/s (default)
    Metadata:
      DURATION        : 00:00:30.744000000
    Stream #0:2: Subtitle: subrip
    Metadata:
      DURATION        : 00:00:30.979000000
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (mp2 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: wrapped_avframe, yuv420p(top coded first (swapped)), 720x576 [SAR 1:1 DAR 5:4], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      DURATION        : 00:00:30.640000000
      encoder         : Lavc58.54.100 wrapped_avframe
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      DURATION        : 00:00:30.744000000
      encoder         : Lavc58.54.100 pcm_s16le
[null @ 0x564fbfbec140] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 930816 >= 930816
[null @ 0x564fbfbec140] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 1456128 >= 1456128
frame=  766 fps=0.0 q=-0.0 Lsize=N/A time=00:00:30.74 bitrate=N/A speed=47.1x    
video:401kB audio:5720kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown



Christmas best wishes

**Comment by kanehekili** [comment]
Yes, you've added an SRT to a matroska container. Cutting this into a container besides mkv will only be possible by transcoding the SRT. I'll look into building it into the ffmpeg backend. The videocut muxer can't do this (haven't found any documentation about libav and SRT)

**Comment by kanehekili** [comment]
Should be fixed with the ffmpeg muxer (turn Videocut muxer off), turn subtitles on. Note that you may have to import new libs
