### ISSUE TITLE
Problems with output errors while saving files.

### ISSUE THREAD

**Issue by buloseshilili** [kanehekili/VideoCut#17]
As in the previous version, still report errors when saving files。Here the logs
Traceback (most recent call last):
  File "C:/Users/Bugs/Desktop/VideoCut-master/src/VideoCut.py", line 2020, in run
    self.function(*self.arguments)
  File "C:/Users/Bugs/Desktop/VideoCut-master/src/VideoCut.py", line 1801, in __directCut
    if self.cutter.setupBinary():
  File "C:\Users\Bugs\Desktop\VideoCut-master\src\FFMPEGTools.py", line 1491, in setupBinary
    fv = FFmpegVersion()
  File "C:\Users\Bugs\Desktop\VideoCut-master\src\FFMPEGTools.py", line 1620, in __init__
    self.figureItOut()
  File "C:\Users\Bugs\Desktop\VideoCut-master\src\FFMPEGTools.py", line 1623, in figureItOut
    result = subprocess.Popen(["/usr/bin/ffmpeg", "-version"], stdout=subprocess.PIPE).communicate()
  File "C:\Users\Bugs\anaconda3\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Bugs\anaconda3\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified.
Like 1.3.2, I found that the error aslo was caused by the Class 'cutter' in 1.3.3, my platform is win11,anaconda , I tried to write a function ‘cut' in the Class 'Cutter' to solve the error. It works on my computer.Here is, in VCCuter.

           def myCut(self, cutlist):
        for index, cutmark in enumerate(cutlist):
            t1 = cutmark[0].timePos
            t2 = cutmark[1].timePos
            cmd = ["ffmpeg","-i", self.config.srcfilePath, "-codec", "copy", "-ss", timedeltaToString2(t1), "-to", timedeltaToString2(t2), self.config.targetPath]
            print(cmd)
            log("cut file:", cmd)
            try:
                executeCmd(cmd)
            except Exception as error:
                self.warn("Remux failed: %s" % (error))
                log("Remux failed", error)
                self.runningProcess = None
                return False
        self.say("Cutting done")
        self.runningProcess = None
        return True
then, in videocut line 1820 Called this function. it works.

**Comment by kanehekili** [comment]
Yes, why don't you select "FFMPEG" instead of remux? (Untick the VideoCut Muxer) The class for ffmpeg remux is called FFMPEGCutter and is automatically selected, if you switch off the VideoCut Muxer. Try it out ;-)

I'm grateful that you test the software on a different environment. So I'll refine my error message, even proposing to select the ffmpeg muxer instead of the (default) Videocut muxer

**Comment by buloseshilili** [comment]
Got it, thanks you very much!

**Comment by kanehekili** [comment]
Got the fix an will release it. Have fun
