### ISSUE TITLE
[enhancement] Change speed 

### ISSUE THREAD

**Issue by uzvaio** [kanehekili/VideoCut#20]
Just found your app and its amazing.
i have a suggestion : 
i dont want to delete some parts.just want to speed up some un-wanted parts.

may you please add this option ?

thanks.

**Comment by kanehekili** [comment]
Thanks for your suggestion.  I can try looking into it, but I'm not sure if that'll work with transcoding (the fast way to copy the packages & alter their timestamps).

**Comment by uzvaio** [comment]
> Thanks for your suggestion. I can try looking into it, but I'm not sure if that'll work with transcoding (the fast way to copy the packages & alter their timestamps).

thanks.
afaik ffmpeg can speed up without encoding. so it is possible.

**Comment by kanehekili** [comment]
Right now, I am spending my time getting German kids from the streets. Our politics fails (but they won't imprison people if they have a different opinion, though)-  so currently I do not have the time to change things. I'm sorry - but the basic idea of open source is: I have an idea, and I'm implementing it. Not: I need something - you have to change it. World sucks today.
