### ISSUE TITLE
remux5 and DVCHD mov

### ISSUE THREAD

**Issue by Randrianasulu** [kanehekili/VideoCut#21]
So, just for kicks I tried to remux this file

./remux5 -i ~/tsMuxer/DVCPROHD_1080i50.qt -s 000.000,002.000 -l eng dvcpro_cut.mov

file itself from

http://samples.mplayerhq.hu/mov/FCP/DVCPROHD_1080i50.mov

for some reason if i cut from 0.0 to 1 sec I see no audio in output, but if I cut to two seconds I see audio, but just 1 sec long )

remux5 was compiled on aarch64/termux against ffmpeg 5.1.2 libs ...

I also wonder if you might like to hack same feature into our ffmpeg-based NLE called Cinelerra-GG, but this is loooong shot.

**Comment by kanehekili** [comment]
Not sure why my comment got lost: I can reproduce it. Audio offset has been changed in ffmpeg 5.x. I'll look into it

**Comment by kanehekili** [comment]
Fixed

**Comment by Randrianasulu** [comment]
thanks, fixed!

I also noticed probably typo in commented out line

 //int channels= in_codecpar->ch_layout>nb_channels;

shouldn't it be  in_codecpar->ch_layout->nb_channels; ?

**Comment by kanehekili** [comment]
correct, but not used currently
