### ISSUE TITLE
Error while trying to save video. 

### ISSUE THREAD

**Issue by RedFraction** [kanehekili/VideoCut#23]
Error while trying to save video with other from ".mp4" file extesion. Original video format .mov. But program automaticly add ".mp4". Make extension of saving video be like in source video.

**Comment by kanehekili** [comment]
Yes, I should change my matrix. Could you tell me which video and audio codec is in your mov file? "mediainfo" would provide the necessary information.

**Comment by RedFraction** [comment]
![image](https://user-images.githubusercontent.com/9009868/227168184-8134c984-240b-428a-901b-f63325307419.png)

Also video example for testing -
https://user-images.githubusercontent.com/9009868/227169449-a530b541-22a0-4ff5-aa5b-40a741664872.mov

**Comment by RedFraction** [comment]
And it would be nice if you also add function, to cut off sound in video.

**Comment by kanehekili** [comment]
Thanks, the audio codec is not compatible with the mp4 container. I'll download that example and will check how to ignore the audio stream altogether.

**Comment by kanehekili** [comment]
Fixed and audio mute implemented.
