### ISSUE TITLE
[FEATURE] - Intervals

### ISSUE THREAD

**Issue by RedFraction** [kanehekili/VideoCut#26]
Greetings, it may be worth adding "_intervals_" for cutting video. I will explain what is it -
The interval has a beginning and an end, everything that includes into it - is included in the final file. One project can have one or more than one intervals. So It replace current start/stop points system, 'cause it will group one start and one stop together. So later we can add some "_processors_" per selected _interval_, like: [video speed control](https://github.com/kanehekili/VideoCut/issues/20), any sound tunnings(for example like I requested in [my last issue](https://github.com/kanehekili/VideoCut/issues/23#issuecomment-1480939581)), and etc. I think this feature will get new **LEVEL_UP** for _VideoCut_. Also would be nice to have some previews of start/stop (or of start only).

If You don't like this idea, please close/cancel/reject this issue.

**Comment by kanehekili** [comment]
Thanks, I'll keep it in mind. Currently I'm working on other projects so I won't have the time. Next on my list will be NLS..
