### ISSUE TITLE
[Feature] - Strict / Not strict timeline

### ISSUE THREAD

**Issue by RedFraction** [kanehekili/VideoCut#29]
It is worth adding the possibility that the pieces of the video could be assembled in a different order, for example, at the beginning a piece from the end, and at the end a piece from the beginning. For those moments when you need a mandatory sequence of frames (Ascending), you can add the STRICT mode.

**Comment by kanehekili** [comment]
Sorry, I can't follow you. The hardest part of the muxer is calculating the timestamps. Checking the C - code you'll probabably realize that your feature is possible, but a hardly feasible. So I will certainly not start refactoring the timestamp calculation. 
Still I very much appreciate your input, providing new ideas for the software.
