### ISSUE TITLE
Error while clicking on the "include from here" button

### ISSUE THREAD

**Issue by Loganavter** [kanehekili/VideoCut#30]
Traceback (most recent call last):
*  File "/usr/bin/videocut", line 1407, in addStartMarker
    self._createVideoCutEntry(pos,VideoCutEntry.MODE_START)
*  File "/usr/bin/videocut", line 1418, in _createVideoCutEntry
    VideoPlugin.setCutEntry(cutEntry)
*  File "/opt/videocut/MpvPlayer.py", line 602, in setCutEntry
    cutEntry.pix = self._makeThumbnail(pilImage)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*  File "/opt/videocut/MpvPlayer.py", line 612, in _makeThumbnail
    pix = QtGui.QPixmap.fromImage(qImage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*TypeError: fromImage(image: QImage, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.AutoColor): argument 1 has unexpected type 'ImageQt'

Arch linux, version videocut-2.2.0-1

**Comment by kanehekili** [comment]
I will look into it - I haven't seen that error before.  Especially because I **expect** ImageQt . Update: PilImage obviously broke it.

**Comment by kanehekili** [comment]
Fixed with 2.2.1 Thank you for setting up the issue.
