### ISSUE TITLE
Doesn't start, error "No module named 'PyQt5.QtOpenGL'"

### ISSUE THREAD

**Issue by greenais** [kanehekili/VideoCut#31]
Debian 11 Bookworm, all dependencies are installed but libmpv1 - there is only libmpv2 in repos, installed in hope to substitute.
Any help, perhaps?

**Comment by kanehekili** [comment]
Sorry, I didn't read my mails the last couple of days. I'll look into it and will report back. Could you please verify if you meant Bookworm Debian **12**, not Debian 11 (bullseye)?

Update
Currently the debs for Ubuntu are build with the following dependencies:
python3, ffmpeg, python3-pyqt5, python3-pil, libmpv1, python3-pyqt5.qtopengl

optional:
qt5-style-plugins. 

I will update my readme. If it works, please close this issue, if not do not hesitate to ask.

**Comment by greenais** [comment]
Sorry, my typo - Deb 12, off cause.
Installation python3-pyqt5.qtopengl resolved the issue, thank you.
