### ISSUE TITLE
Remux error

### ISSUE THREAD

**Issue by Loganavter** [kanehekili/VideoCut#37]
When I try to save the video, I get this: 
Warning!
Remix failed: Err. Seek times out of range. Aborted
Check login .config/Video Cut for details
![2024-05-14_21-39](https://github.com/kanehekili/VideoCut/assets/66126148/5a2a77f5-e853-4897-aeb6-a2d8d41c8236)
[Log file](https://pastebin.com/BdcMaGJe)
When you try to save a video using other methods, it just turns out to be non-reproducible.  
VideoCut version - 3.0.1-1
OS - Endeavouros

**Comment by kanehekili** [comment]
You are using the "Fast" mode and are trying  to cut cut 2 seconds. The logs show no start timestamp (it is '') . Thanks for reporting, that seems to  be a bug.

**Comment by kanehekili** [comment]
Could you give me a link to that video? I can't reproduce the problem - it should be trivial

**Comment by kanehekili** [comment]
Can't reproduce
