### ISSUE TITLE
LRV / LRF (Low res footage) Cutting

### ISSUE THREAD

**Issue by RedFraction** [kanehekili/VideoCut#38]
GoPro(.LRV) and DJI(.LRF) cams have ability to write low resolution footage to make process of video editing more easier. Can U please add feature to cut low res video too simultaneously. It will help much of people. Currently I didnt find this feature in any cutting software. Kdenlive have some patterns to autoload proxy(low res) files for high res videos. Re-encoding is painful... Save Our Souls... - 
![image](https://github.com/kanehekili/VideoCut/assets/9009868/fc876508-d10b-4ad0-8912-a33f83263bb7)
![image](https://github.com/kanehekili/VideoCut/assets/9009868/6c12cdc6-460c-4226-9d4c-3eba7c80a495)
![image](https://github.com/kanehekili/VideoCut/assets/9009868/b23a5afe-b417-47ba-8db7-02756727ef8d)
![image](https://github.com/kanehekili/VideoCut/assets/9009868/4defca40-5f76-4576-803e-068f28ce1448)

**Comment by RedFraction** [comment]
Also it would be nice if VideoCut will use LRF/LRV for preview, cause it have big problems with performance while running(playing) hi res videos.

**Comment by kanehekili** [comment]
Holy cow - I have never heard of that. Could you provide a recorded example and some Link about LRF/LRV. Note: videocut is based on ffmpeg - if the library does not support that, I can't implement it.

**Comment by RedFraction** [comment]
> Holy cow - I have never heard of that. Could you provide a recorded example and some Link about LRF/LRV. Note: videocut is based on ffmpeg - if the library does not support that, I can't implement it.

Sorry can't provide u videos via GitHub. But you can check my cloud drive - https://disk.yandex.ru/a/c7pjKKMzLCGndA. Or u can try to find other examples on internet. There is one full size raw video(GX) from gopro (.mp4), and one compressed/low resolution video, also from gopro (.lrv). ffmpeg supports all this files. (VideoCut too, read next)

P.S. I have already cutted a couple of videos via the following scenario - 
First I opened the .lrv (GL* prefix), created the time markup using VideoCut, saved cutted compressed version, then closed app, renamed the .xml file created while the program was running, changing the prefix to (GX*), and then I've opened it with a full-size video (GX*) and clicked save to get cutted full-resolution video. But it is very difficult and time-consuming.

**Comment by RedFraction** [comment]
Some info about .lrv - https://actioncamphotographer.com/gopro-video-lrv-thm-files/
And video example how to use it(.lrv - proxy) with kdenlive - https://www.youtube.com/watch?v=gWvZoDiWsI0&ab_channel=GeekOutdoors

**Comment by RedFraction** [comment]
If u need any other info or help you can contact me via telegram in my bio.

**Comment by RedFraction** [comment]
Any updates?

**Comment by kanehekili** [comment]
Fmpeg could work with the mp4 files but not with LRV/LRF as described [here](https://alexbevi.com/blog/2023/12/21/combine-gopro-files-with-ffmpeg/)
Quote:
`
The LRV files are low-resolution video files used by GoPros as video previews. You can safely delete both filetypes–they'll be regenerated from the original MP4 or image file if needed.
Further more it should be possible just to rename the "lrv" files into mp4 and process them

`
So working with the mp4 files should suffice? Currently I'm not planning to add features to this project. As an Open Source project I'll welcome merge requests from others.

**Comment by RedFraction** [comment]
Ok, I understand your point of view. 

But You've lost the point of using lrv. 
1. lrv is also mp4, just other naming to determine that is low res footage of full resolution video, and of course it is supported by ffmpef. I even gave a case of how it can be used without any changes to the project code, but it's pain.
2. lrv is for preview purposes only. It requires fewer resources during playback and all kinds of manipulations, such as color grading. Because the same video but in full-size (4k-5.3k) with more bigger color depth, framerate and bitrate is plaing with lags (only in videocut, and other editing software). And after all corrections on low res there are should be applied while render but on full res.

I will try to find some foreign devs.

**Comment by kanehekili** [comment]
I concur - it is a pain, since ffmpeg has no concept of matching file endings and codecs. As I wrote above: lrv is an mp4 (in low res) - but Videocut will not recognize that format by its file extension. Extensions to my code are welcome, send a merge request if you have a solution. So processing should work, if you rename the ending to mp4, process it and rename it to lrf again.
