### ISSUE TITLE
language error

### ISSUE THREAD

**Issue by moebius1** [kanehekili/VideoCut#8]
Bonjour,

I'm french and like original version movies with original language and french subtitles but, when editing a m2t file (kaffeine dvt-tv one) with videocut, I get this error and no selection of language and subtitle when playing back :
Traceback (most recent call last):
*  File "/usr/local/bin/VideoCut", line 806, in openLanguageSettings
    dlg = LanguageSettingsDialog(self, lang, langMap, self._videoController.getLanguages())
*  File "/usr/local/bin/VideoCut", line 1176, in __init__
    self.setupLanguages(defCodes,available3LetterCodes)
*  File "/usr/local/bin/VideoCut", line 1349, in setupLanguages
    self.avail.append(codeToLang[code])
*KeyError: 'qaa'

cordialement,

**Comment by kanehekili** [comment]
Thanks for reporting. Looks like my list does not contain qaa as language code. ISO 639-2 defines "qaa-qtz" as "Reserved for local use" - so I did not expect a code not in the list (which is a bug). Which language did you expect?

It would help me (for my muxer, not the python code) if you could provide a small part of the film (as attachment here). In the terminal could you execute:

`ffmpeg -i yourFile.mp4 -t 60 -vcodec copy -acodec copy -scodec copy out.mp4`

This command would cut the first 60 seconds of the video that failed into out.mp4, which you could attach. 

Cutting of subtitles will be included in the next version (ffmpeg muxer only) , together with a fix of the unknown language code.

**Comment by kanehekili** [comment]
Release 1.2.8 supporting subtitles.
