### ISSUE TITLE
Error when atempting saving

### ISSUE THREAD

**Issue by moebius1** [kanehekili/VideoCut#9]
Bonjour,
Hum, I couldn't test because of an error occurring :
![Capture du 2021-04-24 09-47-00](https://user-images.githubusercontent.com/1695176/115951689-56c13980-a4e2-11eb-805a-dbc6888ce4c2.png)
 cordialement,

**Comment by kanehekili** [comment]
Yes, probably a conversion problem from mkv to mp4. Please provide the log, which can be found in `/usr/local/bin/videocut/data/VC.log`.

**Comment by moebius1** [comment]
Ok, hereit is :

2021-04-24 09:46:21,688 FFmepg Version: 4.3
2021-04-24 09:46:21,690 cut file: 
['/usr/local/bin/videocut/ffmpeg/bin/V4/remux5', '-i', 
'/disque2/espace3/télé/b/Welcome back.m2t', '-s', '122.760,174.480', 
'/disque2/espace3/télé/b/Welcome back-cut.mpg']
2021-04-24 09:46:21,765 > Err: Write header: Invalid argument
2021-04-24 09:46:21,768 Remux failed Command 
'['/usr/local/bin/videocut/ffmpeg/bin/V4/remux5', '-i', 
'/disque2/espace3/télé/b/Welcome back.m2t', '-s', '122.760,174.480', 
'/disque2/espace3/télé/b/Welcome back-cut.mpg']' returned non-zero exit 
status 1.

Previous attempt :

2021-04-24 09:45:23,026 FFmepg Version: 4.3
2021-04-24 09:45:23,030 cut file: 
['/usr/local/bin/videocut/ffmpeg/bin/V4/remux5', '-i', 
'/disque2/espace3/télé/b/Welcome back.m2t', '-s', '122.760,155.080', 
'/disque2/espace3/télé/b/Welcome back.mpg']
2021-04-24 09:45:23,105 > Err: Write header: Invalid argument
2021-04-24 09:45:23,108 Remux failed Command 
'['/usr/local/bin/videocut/ffmpeg/bin/V4/remux5', '-i', 
'/disque2/espace3/télé/b/Welcome back.m2t', '-s', '122.760,155.080', 
'/disque2/espace3/télé/b/Welcome back.mpg']' returned non-zero exit 
status 1.

cordialement,

Le 24/04/2021 à 13:53, Kanehekili a écrit :

**Comment by kanehekili** [comment]
Thanks, I will look into it.

moebius1 ***@***.***> schrieb am Sa., 24. Apr. 2021, 15:36:

**Comment by kanehekili** [comment]
Trying all of my mpg TS streams do not show any error. Could you upload part of that m2t file? Easiest would be:
`ffmpeg -i  '/disque2/espace3/télé/b/Welcome back.m2t'  -t 60  -c:a copy -c:v copy -c:s copy  test.m2t`. 
This creates a 60 seconds video that has most (but not all) streams of that m2t file.  
It would help me to solve this error.

Merci bien
Kanehekili

**Comment by kanehekili** [comment]
Could you also paste the output of 
`ffmepg -i  '/disque2/espace3/télé/b/Welcome back.m2t'` - it will log the complete stream info of the orginal file.  

Merci beaucoup
Kanehekili

**Comment by moebius1** [comment]
Very good french ! :-)
here it is :
ffmpeg -i '/disque2/espace3/télé/b/Welcome back.m2t'
ffmpeg version 4.3.2-0+deb11u1 Copyright (c) 2000-2021 the FFmpeg developers
   built with gcc 10 (Debian 10.2.1-6)
   configuration: --prefix=/usr --extra-version=0+deb11u1 
--toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu 
--incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl 
--disable-stripping --enable-avresample --disable-filter=resample 
--enable-gnutls --enable-ladspa --enable-libaom --enable-libass 
--enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio 
--enable-libcodec2 --enable-libdav1d --enable-libflite 
--enable-libfontconfig --enable-libfreetype --enable-libfribidi 
--enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame 
--enable-libmysofa --enable-libopenjpeg --enable-libopenmpt 
--enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg 
--enable-librubberband --enable-libshine --enable-libsnappy 
--enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh 
--enable-libtheora --enable-libtwolame --enable-libvidstab 
--enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp 
--enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq 
--enable-libzvbi --enable-lv2 --enable-omx --enable-openal 
--enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx 
--enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 
--enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
   libavutil      56. 51.100 / 56. 51.100
   libavcodec     58. 91.100 / 58. 91.100
   libavformat    58. 45.100 / 58. 45.100
   libavdevice    58. 10.100 / 58. 10.100
   libavfilter     7. 85.100 /  7. 85.100
   libavresample   4.  0.  0 /  4.  0.  0
   libswscale      5.  7.100 /  5.  7.100
   libswresample   3.  7.100 /  3.  7.100
   libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] non-existing PPS 0 referenced
     Last message repeated 1 times
[h264 @ 0x55d4873424c0] decode_slice_header error
[h264 @ 0x55d4873424c0] no frame!
[h264 @ 0x55d4873424c0] mmco: unref short failure
     Last message repeated 1 times
[mpegts @ 0x55d48733c1c0] PES packet size mismatch
[mpegts @ 0x55d48733c1c0] Packet corrupt (stream = 1, dts = 69934323).
[mpegts @ 0x55d48733c1c0] PES packet size mismatch
[mpegts @ 0x55d48733c1c0] Packet corrupt (stream = 2, dts = 69934323).
[mpegts @ 0x55d48733c1c0] PES packet size mismatch
[mpegts @ 0x55d48733c1c0] Packet corrupt (stream = 3, dts = 69931443).
Input #0, mpegts, from '/disque2/espace3/télé/b/Welcome back.m2t':
   Duration: 01:47:43.28, start: 89758.589722, bitrate: 4810 kb/s
   Program 1025
     Stream #0:0[0x78]: Video: h264 (High) ([27][0][0][0] / 0x001B), 
yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 
tbr, 90k tbn, 50 tbc
     Stream #0:1[0x82](fra): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 
Hz, stereo, fltp, 192 kb/s
     Stream #0:2[0x83](fra): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 
Hz, stereo, fltp, 96 kb/s (visual impaired) (descriptions)
     Stream #0:3[0x84](qaa): Audio: eac3 ([6][0][0][0] / 0x0006), 48000 
Hz, stereo, fltp, 128 kb/s
     Stream #0:4[0x8c](fra): Subtitle: dvb_subtitle ([6][0][0][0] / 
0x0006) (hearing impaired)
     Stream #0:5[0x8d](fra): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
At least one output file must be specified


Le 24/04/2021 à 21:34, Kanehekili a écrit :

**Comment by kanehekili** [comment]
OK, that is a h264 Video with eac3 Audio codec. I've made an error by providing "mpg" as default extension for "transport streams". Could you retry your conversion by setting the target extension to ".mp4"? (Just edit the extension when saving).
The mistake is, that mpg cannot hold an eac3 audio codec. I've already fixed the extension part.
If that does not work, I would need a sample of the file, as described above... 

My french is a little rusty, I've learned it in school. The best french teacher I've ever had came from France.. 
Merci pour votre aide aujourd'hui
Cordialement
Kanehekili

**Comment by kanehekili** [comment]
I could find a video with eac3 - if the extension was mpg it fails with "Write header" ...  With mp4 it worked. I'll push the new version that will not propose "mpg" on "AVCH" transport streams...

**Comment by moebius1** [comment]
Ok, the file is here :
http://dl.free.fr/kNn1bIWao
good night


Le 24/04/2021 à 21:01, Kanehekili a écrit :

**Comment by kanehekili** [comment]
Merci moebius1 - I could confirm the problem - but I do not read the subtitles. I'll use that file to find out why it does not work...

**Comment by kanehekili** [comment]
Version1.2.9 will provide you with the correct extensions, but DVB_SUBTITLE is not a part of that suite. I'll try to solve that puzzle, but it will take some time. It looks like I have to re-encode it (which is exactly what I don't want - VideoCut is supposed to be a very fast remuxer) 
I'll close this issue, but will open a new one - citing your request to support DVB_SUBTITLE streams
